#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface FlexRIC service
#   Valid for Ubuntu-22.04 (jammy)
#
#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:jammy

# FROM $BASE_IMAGE AS oai-flexric-base
# ENV DEBIAN_FRONTEND=noninteractive
# ENV TZ=Europe/Paris

# #install developers pkg/repo
# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
#     DEBIAN_FRONTEND=noninteractive apt-get install --yes \
#        build-essential \
#        libsctp-dev \
#        git \
#        wget \
#        tar \
#        m4 \
#        automake \
#        libtool \
#        python3 \
#        cmake \
#        cmake-curses-gui \
#        bison \
#        flex \
#        gdb \
#        libpcre2-dev \
#        python3-dev \
#        python3-pip \
#        gcc-12 \
#        g++-12 \
#        mold \
#        ninja-build && \
#     apt-get clean

# RUN git clone https://github.com/swig/swig.git && \
#     cd swig && \
#     git checkout release-4.1 && \
#     ./autogen.sh && \
#     ./configure --prefix=/usr/ && \
#     make -j8 && \
#     make install && \
#     ldconfig

# FROM oai-flexric-base AS oai-flexric-builder
# ARG E2AP_VERSION=E2AP_V3
# ARG KPM_VERSION=KPM_V3_00

# WORKDIR /flexric

# RUN git clone https://gitlab.eurecom.fr/mosaic5g/flexric /flexric
# WORKDIR /flexric
# RUN git checkout dev 

# COPY ./flexric .
# RUN mkdir build && \
#     cd build && \
#     cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
#           -DE2AP_VERSION=$E2AP_VERSION \
#           -DKPM_VERSION=$KPM_VERSION \
#           -DCMAKE_C_FLAGS_RELEASE="-O3" \
#           -DCMAKE_CXX_FLAGS_RELEASE="-O3" \
#           -DCMAKE_C_COMPILER=gcc-12 \
#           -DCMAKE_CXX_COMPILER=g++-12 .. && \
#     ninja && \
#     ninja install && \
#     echo "--- Check shared objects dependencies for executable nearRT-RIC ---" && \
#     ldd /flexric/build/examples/ric/nearRT-RIC && \
#     echo "--- Check shared objects dependencies for xApp shared library ---" && \
#     ldd /flexric/build/src/xApp/libe42_xapp_shared.so

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------

FROM $BASE_IMAGE AS oai-flexric
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV XAPP_DURATION=-1
ARG E2AP_VERSION=E2AP_V2
ARG KPM_VERSION=KPM_V2_03

# Comnetsemu integration
#&& apt upgrade -y
RUN apt-get update  && \
    apt-get install -y --no-install-recommends --fix-missing \
    apt-utils net-tools iputils-ping  \
    bash bash-completion ethtool \
    iproute2 busybox-static iperf \
    stress-ng curl tcpdump netcat-openbsd \
    libssl-dev libsctp-dev && \
    apt-get autoremove -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/*

#install pkg needed to run
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes --fix-missing \
       psmisc \
       gpg \
       wget \
       libsctp1 \
       libsctp-dev \
       python3 \
       python3-pip \
       build-essential \
       libsctp-dev \
       git \
       wget \
       tar \
       m4 \
       automake \
       libtool \
       cmake \
       cmake-curses-gui \
       bison \
       flex \
       gdb \
       libpcre2-dev \
       software-properties-common \
       #python3-dev \
       python3.10-dev \
       asn1c \
       python3-pip && \
       apt-get clean
       ## apt-get autoremove -y && \
       ## apt-get autoclean -y
       
RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt update && \
    apt install -y \
    build-essential \
    ninja-build \
    gcc-13 \
    g++-13 \
    mold 

# and alternatives
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-13 \
    --slave /usr/bin/gcov gcov /usr/bin/gcov-13 && \
    update-alternatives --config gcc

# flatbuffer cc install
RUN git clone https://github.com/dvidelabs/flatcc.git && \
    cd flatcc && \
    ./scripts/initbuild.sh make && \
    ./scripts/setup.sh -a ../mymonster && \
    cd ../mymonster && \
    ./scripts/build.sh 

RUN git clone https://github.com/swig/swig.git && \
    cd swig && \
    git checkout release-4.1 && \
    ./autogen.sh && \
    ./configure --prefix=/usr/ && \
    make -j8 && \
    make install

RUN rm -rf /tmp/asn1c && \
    git clone https://github.com/mouse07410/asn1c /tmp/asn1c && \
    cd /tmp/asn1c && \
    git checkout 940dd5fa9f3917913fd487b13dfddfacd0ded06e && \
    # Showing which version is used
    git log -n1 && \
    autoreconf -iv && \
    ./configure --prefix /opt/asn1c/ && \
    make -j`nproc` && \
    make install

ENV PATH="/opt/asn1c/bin:${PATH}"
#compile flexric
WORKDIR /
COPY ./flexric ./flexric
RUN mkdir /flexric/build && \
    cd /flexric/build && \
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_ASN1C_EXECUTABLE=/opt/asn1c/bin/asn1c \
          -DE2AP_VERSION=$E2AP_VERSION \
          -DKPM_VERSION=$KPM_VERSION \
          -DXAPP_MULTILANGUAGE=ON \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_C_FLAGS_RELEASE="-O3" \
          -DCMAKE_CXX_FLAGS_RELEASE="-O3" \
          -DCMAKE_C_COMPILER=gcc-13 \
          -DCMAKE_CXX_COMPILER=g++-13 .. && \
          ninja && \
          ninja install
          #ctest -j8 --output-on-failure
#RUN cd ../ && make install 

RUN ldconfig && \
    echo "--- Check shared objects dependencies for executable nearRT-RIC ---" && \
    ldd /flexric/build/examples/ric/nearRT-RIC && \
    echo "--- Check shared objects dependencies for xApp shared library ---" && \
    ldd /flexric/build/src/xApp/libe42_xapp_shared.so 


RUN cp -r /flexric/build/examples/ric/nearRT-RIC /usr/local/bin/ && \
#    mkdir -p /usr/local/flexric/xApp && \
    cp -r /flexric/build/examples/xApp /usr/local/flexric/ && \
    mkdir -p /usr/local/flexric/emulator/agent && \
    cp -r /flexric/build/examples/emulator/agent /usr/local/flexric/emulator/



# COPY --from=oai-flexric-builder \
#     /usr/local/lib/flexric/libmac_sm.so \
#     /usr/local/lib/flexric/libkpm_sm.so \
#     /usr/local/lib/flexric/librlc_sm.so \
#     /usr/local/lib/flexric/libslice_sm.so \
#     /usr/local/lib/flexric/libtc_sm.so \
#     /usr/local/lib/flexric/libgtp_sm.so \
#     /usr/local/lib/flexric/libpdcp_sm.so \
#     /usr/local/lib/flexric/librc_sm.so \
#     /usr/local/lib/flexric/

# COPY --from=oai-flexric-builder \
#     /flexric/build/src/xApp/libe42_xapp_shared.so \
#     /flexric/build/src/xApp/

# COPY --from=oai-flexric-builder \
#     /flexric/build/examples/ric/nearRT-RIC /usr/local/bin/nearRT-RIC

# ## Copy xApps
# COPY --from=oai-flexric-builder \
#     /flexric/build/examples/xApp /usr/local/flexric/xApp

## E2
EXPOSE 36421/sctp
## E42
EXPOSE 36422/sctp

COPY ./volumes/flexric_gnb.conf /usr/local/etc/flexric/flexric_gnb.conf
COPY ./volumes/flexric_cu.conf /usr/local/etc/flexric/flexric_cu.conf
COPY ./volumes/flexric_du.conf /usr/local/etc/flexric/flexric_du.conf
COPY ./volumes/flexric_cucp.conf /usr/local/etc/flexric/flexric_cucp.conf
COPY ./volumes/flexric_cuup.conf /usr/local/etc/flexric/flexric_cuup.conf
COPY ./volumes/ric.conf /usr/local/etc/flexric/ric.conf
COPY ./volumes/ric.conf /usr/local/etc/flexric/flexric.conf

RUN echo "--- Check shared objects dependencies for flexric shared libraries ---" && \
    ls /usr/local/lib/flexric/ && \
    ldd /usr/local/lib/flexric/*.so 

WORKDIR /flexric/build

ENTRYPOINT [""]
#CMD ["/bin/bash"]
CMD ["/bin/bash", "-c", "sleep infinity"]
#CMD ["stdbuf", "-o0", "nearRT-RIC"]
